name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup
        uses: ./.github/actions/setup-action
      # skip for now. so many linting errors
      # - run: "npx eslint 'src/**/*.{js,jsx}' --rule 'prettier/prettier: warn'"
  build:
    name: Build the craco app
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup
        uses: ./.github/actions/setup-action
      - run: npm ls
      - run: npm run build # build is failing on lint; added skip in sample env :(
  coverage:
    name: Test and publish test coverage
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup
        uses: ./.github/actions/setup-action
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: cobertura.xml
