name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Install and build the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: cp .env.sample .env
      # - run: npx craco build # build is failing :(
  lint:
    name: Linting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npx eslint 'src/**/*.{js,jsx}'
  coverage:
    name: Test and publish test coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing"
