name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Install and build the app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: cp .env.sample .env
      - run: npm run build
  lint:
    name: Linting
    needs: build
    steps:
      - run: npx eslint 'src/**/*.{js,jsx}'
  coverage:
    name: Test and publish test coverage
    needs: build
    steps:
      - run: echo "testing"
