name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-action.yml
      - run: "npx eslint 'src/**/*.{js,jsx}' --rule 'prettier/prettier: 1'"
  build:
    name: Install and build the app
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - id: build
        uses: ./.github/actions/build-action.yml
      - run: npx craco build # build is failing on lint; added skip in sample env :(
  coverage:
    name: Test and publish test coverage
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build-action.yml
      - run: echo "testing"
