name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Install and build the app
    uses: ./.github/workflows/build.yml
    steps:
      - run: npx craco build # build is failing on lint; added skip in sample env :(
  lint:
    name: Linting
    needs: build
    uses: ./.github/workflows/build.yml
    steps:
      - run: "npx eslint 'src/**/*.{js,jsx}' --rule 'prettier/prettier: 1'"
  coverage:
    name: Test and publish test coverage
    needs: build
    uses: ./.github/workflows/build.yml
    steps:
      - run: echo "testing"
